# Generated by Django 4.2.7 on 2025-10-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_correspondent_documenttype_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('imap_server', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('tag', 'Apply Tag'), ('correspondent', 'Set Correspondent'), ('doctype', 'Set Document Type'), ('notify', 'Send Notification'), ('archive', 'Archive Document')], max_length=20)),
                ('action_value', models.CharField(blank=True, max_length=255)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttype')),
                ('tags', models.ManyToManyField(blank=True, to='documents.tag')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='EmailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('subject_contains', models.CharField(blank=True, max_length=255)),
                ('sender_contains', models.CharField(blank=True, max_length=255)),
                ('body_contains', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('tag', 'Apply Tag'), ('correspondent', 'Set Correspondent'), ('doctype', 'Set Document Type'), ('delete', 'Delete Email'), ('move', 'Move to Folder')], max_length=20)),
                ('action_value', models.CharField(blank=True, max_length=255)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.emailaccount')),
            ],
        ),
    ]
