# Generated by Django 4.2.7 on 2025-10-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareditem',
            name='permission_level',
        ),
        migrations.AddField(
            model_name='shareditem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='permission_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
