# Generated by Django 4.2.7 on 2025-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_correspondent_documenttype_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
