# Generated by Django 4.2.7 on 2025-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_shareditem_permission_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='folder',
            name='path',
            field=models.TextField(blank=True),
        ),
    ]
