# Generated by Django 5.2.7 on 2025-10-09 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='User address', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='User employee ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, help_text='User job title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locale',
            field=models.CharField(blank=True, help_text='User locale', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='User manager', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, help_text='User middle name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='User phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='start_date',
            field=models.DateField(blank=True, help_text='User start date', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suffix',
            field=models.CharField(blank=True, help_text='User suffix (e.g., Jr., Sr., III)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, help_text='User timezone', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Department creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Department last update timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if department is active')),
                ('owner', models.ForeignKey(blank=True, help_text='Department owner/head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_departments', to=settings.AUTH_USER_MODEL)),
                ('parent_department', models.ForeignKey(blank=True, help_text='Parent department for hierarchical structure', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
